import { useParams, useSearchParams } from 'react-router-dom';
import { usePlayerCVBySlug } from '@/hooks/usePlayerCV';
import { useEffect } from 'react';
import { Link2, Trophy, TrendingUp, Target, Zap } from 'lucide-react';

export default function PublicCVPage() {
  const { slug } = useParams<{ slug: string }>();
  const [searchParams] = useSearchParams();
  const { data: cv, isLoading } = usePlayerCVBySlug(slug || null);
  const isPrint = searchParams.get('print') === '1';

  useEffect(() => {
    if (isPrint && cv) {
      setTimeout(() => window.print(), 500);
    }
  }, [isPrint, cv]);

  if (isLoading) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center">
        <div className="animate-spin h-8 w-8 border-2 border-gray-900 border-t-transparent rounded-full" />
      </div>
    );
  }

  if (!cv) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center text-gray-500">
        CV not found or not published.
      </div>
    );
  }

  const template = cv.template || 'classic';

  if (template === 'dark') return <DarkPublicCV cv={cv} />;
  if (template === 'minimal') return <MinimalPublicCV cv={cv} />;
  return <ClassicPublicCV cv={cv} />;
}

// ─── Classic Template ───
function ClassicPublicCV({ cv }: { cv: any }) {
  return (
    <div className="min-h-screen bg-white text-gray-900 print:bg-white">
      <div className="max-w-[800px] mx-auto p-8 sm:p-12">
        <div className="border-b-2 border-gray-900 pb-6 mb-8">
          <h1 className="text-4xl font-bold tracking-tight text-gray-900">{cv.full_name}</h1>
          <p className="text-lg font-semibold text-gray-600 mt-1">{cv.position}</p>
          <p className="text-sm text-gray-500">{cv.current_team}</p>
        </div>

        <div className="grid grid-cols-4 gap-4 mb-8 text-sm">
          {[
            { label: 'Age', value: cv.age },
            { label: 'Height', value: `${cv.height}cm` },
            { label: 'Weight', value: `${cv.weight}kg` },
            { label: 'Preferred Foot', value: cv.preferred_foot },
          ].map(item => (
            <div key={item.label} className="border border-gray-200 rounded p-3 text-center">
              <p className="text-[10px] uppercase tracking-wider text-gray-400">{item.label}</p>
              <p className="font-semibold text-gray-900 mt-0.5">{item.value}</p>
            </div>
          ))}
        </div>

        {cv.bio && (
          <div className="mb-8">
            <h3 className="text-[11px] uppercase tracking-widest text-gray-400 mb-2 font-semibold">Profile</h3>
            <p className="text-sm text-gray-700 leading-relaxed">{cv.bio}</p>
          </div>
        )}

        {cv.previous_teams?.length > 0 && (
          <div className="mb-8">
            <h3 className="text-[11px] uppercase tracking-widest text-gray-400 mb-2 font-semibold">Previous Teams</h3>
            <div className="flex flex-wrap gap-2">
              {cv.previous_teams.map((t: string, i: number) => (
                <span key={i} className="px-3 py-1 bg-gray-100 text-gray-700 rounded text-sm">{t}</span>
              ))}
            </div>
          </div>
        )}

        {cv.achievements?.length > 0 && (
          <div className="mb-8">
            <h3 className="text-[11px] uppercase tracking-widest text-gray-400 mb-2 font-semibold">Achievements</h3>
            <ul className="space-y-1">
              {cv.achievements.map((a: string, i: number) => (
                <li key={i} className="text-sm text-gray-700 flex items-center gap-2">
                  <div className="w-1.5 h-1.5 rounded-full bg-gray-900" />
                  {a}
                </li>
              ))}
            </ul>
          </div>
        )}

        {cv.highlight_video_url && (
          <div className="mb-8">
            <h3 className="text-[11px] uppercase tracking-widest text-gray-400 mb-2 font-semibold">Highlights</h3>
            <a href={cv.highlight_video_url} target="_blank" rel="noopener noreferrer"
              className="inline-flex items-center gap-2 text-sm text-blue-600 hover:underline">
              <Link2 className="h-3.5 w-3.5" /> Watch Highlight Reel
            </a>
          </div>
        )}

        <div className="border-t border-gray-200 pt-6 mt-12 text-center">
          <p className="text-[10px] uppercase tracking-widest text-gray-400">Generated by Camino — Player Development Platform</p>
        </div>
      </div>
    </div>
  );
}

// ─── Dark Template ───
function DarkPublicCV({ cv }: { cv: any }) {
  const metrics = [
    { label: 'Technical', icon: Target, color: '#3b82f6' },
    { label: 'Tactical', icon: Zap, color: '#8b5cf6' },
    { label: 'Physical', icon: TrendingUp, color: '#10b981' },
    { label: 'Mental', icon: Trophy, color: '#f59e0b' },
  ];

  return (
    <div className="min-h-screen print:bg-white" style={{ background: '#0a0e1a' }}>
      <div className="max-w-[800px] mx-auto p-8 sm:p-12">
        {/* Header */}
        <div className="relative pb-8 mb-8" style={{ borderBottom: '1px solid #1e2540' }}>
          <div className="absolute inset-0 opacity-10" style={{ background: 'radial-gradient(circle at 80% 20%, #3b82f6, transparent 60%)' }} />
          <div className="relative flex items-start justify-between">
            <div>
              <p className="text-[10px] uppercase tracking-[0.3em] mb-2" style={{ color: '#3b82f6' }}>Player Profile</p>
              <h1 className="text-4xl font-black tracking-tight text-white">{cv.full_name}</h1>
              <div className="flex items-center gap-3 mt-2">
                <span className="text-sm font-semibold" style={{ color: '#3b82f6' }}>{cv.position}</span>
                <span className="w-1 h-1 rounded-full" style={{ background: '#ffffff20' }} />
                <span className="text-sm" style={{ color: '#ffffff50' }}>{cv.current_team}</span>
              </div>
            </div>
          </div>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-4 gap-3 mb-8">
          {[
            { label: 'Age', value: cv.age },
            { label: 'Height', value: `${cv.height}cm` },
            { label: 'Weight', value: `${cv.weight}kg` },
            { label: 'Foot', value: cv.preferred_foot },
          ].map(item => (
            <div key={item.label} className="rounded-lg p-3 text-center" style={{ background: '#111628', border: '1px solid #1e2540' }}>
              <p className="text-[9px] uppercase tracking-widest" style={{ color: '#ffffff30' }}>{item.label}</p>
              <p className="font-bold text-white mt-1 text-sm">{item.value}</p>
            </div>
          ))}
        </div>

        {cv.bio && (
          <div className="mb-8">
            <h3 className="text-[10px] uppercase tracking-[0.2em] mb-2" style={{ color: '#3b82f6' }}>Profile</h3>
            <p className="text-sm leading-relaxed" style={{ color: '#ffffff60' }}>{cv.bio}</p>
          </div>
        )}

        {cv.previous_teams?.length > 0 && (
          <div className="mb-8">
            <h3 className="text-[10px] uppercase tracking-[0.2em] mb-2" style={{ color: '#3b82f6' }}>Previous Teams</h3>
            <div className="flex flex-wrap gap-2">
              {cv.previous_teams.map((t: string, i: number) => (
                <span key={i} className="px-3 py-1 rounded-md text-xs font-medium" style={{ background: '#111628', border: '1px solid #1e2540', color: '#ffffff70' }}>{t}</span>
              ))}
            </div>
          </div>
        )}

        {cv.achievements?.length > 0 && (
          <div className="mb-8">
            <h3 className="text-[10px] uppercase tracking-[0.2em] mb-2" style={{ color: '#3b82f6' }}>Achievements</h3>
            <ul className="space-y-1.5">
              {cv.achievements.map((a: string, i: number) => (
                <li key={i} className="text-sm flex items-center gap-2" style={{ color: '#ffffff60' }}>
                  <div className="w-1.5 h-1.5 rounded-full" style={{ background: '#3b82f6' }} />
                  {a}
                </li>
              ))}
            </ul>
          </div>
        )}

        {cv.highlight_video_url && (
          <div className="mb-8">
            <h3 className="text-[10px] uppercase tracking-[0.2em] mb-2" style={{ color: '#3b82f6' }}>Highlights</h3>
            <a href={cv.highlight_video_url} target="_blank" rel="noopener noreferrer"
              className="inline-flex items-center gap-2 text-sm hover:underline" style={{ color: '#3b82f6' }}>
              <Link2 className="h-3.5 w-3.5" /> Watch Highlight Reel
            </a>
          </div>
        )}

        <div className="text-center pt-6 mt-12" style={{ borderTop: '1px solid #1e2540' }}>
          <p className="text-[9px] uppercase tracking-[0.3em]" style={{ color: '#ffffff15' }}>Generated by Camino — Player Development Platform</p>
        </div>
      </div>
    </div>
  );
}

// ─── Minimal Gold Template ───
function MinimalPublicCV({ cv }: { cv: any }) {
  const accent = '#E8B400';

  return (
    <div className="min-h-screen bg-white print:bg-white">
      <div className="max-w-[800px] mx-auto p-8 sm:p-12">
        {/* Header with gold accent */}
        <div className="flex mb-8 pb-8" style={{ borderBottom: '1px solid #f0f0f0' }}>
          <div className="w-1 shrink-0 rounded-full mr-6" style={{ background: accent }} />
          <div className="flex-1 flex items-start justify-between">
            <div>
              <h1 className="text-4xl font-bold tracking-tight text-gray-900">{cv.full_name}</h1>
              <p className="text-sm font-semibold mt-1" style={{ color: accent }}>{cv.position}</p>
              <p className="text-xs text-gray-400 mt-0.5">{cv.current_team}</p>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-4 gap-6 text-center mb-8">
          {[
            { label: 'Age', value: cv.age },
            { label: 'Height', value: `${cv.height}cm` },
            { label: 'Weight', value: `${cv.weight}kg` },
            { label: 'Foot', value: cv.preferred_foot },
          ].map(item => (
            <div key={item.label}>
              <p className="text-[9px] uppercase tracking-widest text-gray-300">{item.label}</p>
              <p className="font-semibold text-gray-900 mt-0.5 text-sm">{item.value}</p>
            </div>
          ))}
        </div>

        {cv.bio && (
          <div className="mb-8">
            <h3 className="text-[10px] uppercase tracking-[0.2em] font-semibold mb-2" style={{ color: accent }}>Profile</h3>
            <p className="text-sm text-gray-500 leading-relaxed">{cv.bio}</p>
          </div>
        )}

        {cv.previous_teams?.length > 0 && (
          <div className="mb-8">
            <h3 className="text-[10px] uppercase tracking-[0.2em] font-semibold mb-2" style={{ color: accent }}>Previous Teams</h3>
            <div className="flex flex-wrap gap-2">
              {cv.previous_teams.map((t: string, i: number) => (
                <span key={i} className="px-3 py-1 rounded text-xs font-medium text-gray-600" style={{ background: '#faf5e4', border: `1px solid ${accent}30` }}>{t}</span>
              ))}
            </div>
          </div>
        )}

        {cv.achievements?.length > 0 && (
          <div className="mb-8">
            <h3 className="text-[10px] uppercase tracking-[0.2em] font-semibold mb-2" style={{ color: accent }}>Achievements</h3>
            <ul className="space-y-1">
              {cv.achievements.map((a: string, i: number) => (
                <li key={i} className="text-sm text-gray-500 flex items-center gap-2">
                  <div className="w-1.5 h-1.5 rounded-full" style={{ background: accent }} />
                  {a}
                </li>
              ))}
            </ul>
          </div>
        )}

        {cv.highlight_video_url && (
          <div className="mb-8">
            <h3 className="text-[10px] uppercase tracking-[0.2em] font-semibold mb-2" style={{ color: accent }}>Highlights</h3>
            <a href={cv.highlight_video_url} target="_blank" rel="noopener noreferrer"
              className="inline-flex items-center gap-2 text-sm hover:underline" style={{ color: accent }}>
              <Link2 className="h-3.5 w-3.5" /> Watch Highlight Reel
            </a>
          </div>
        )}

        <div className="text-center pt-6 mt-12" style={{ borderTop: '1px solid #f0f0f0' }}>
          <p className="text-[9px] uppercase tracking-[0.3em] text-gray-300">Generated by Camino — Player Development Platform</p>
        </div>
      </div>
    </div>
  );
}
