import { useParams, useSearchParams } from 'react-router-dom';
import { usePlayerCVBySlug } from '@/hooks/usePlayerCV';
import { useEffect } from 'react';

import { Link2 } from 'lucide-react';

export default function PublicCVPage() {
  const { slug } = useParams<{ slug: string }>();
  const [searchParams] = useSearchParams();
  const { data: cv, isLoading } = usePlayerCVBySlug(slug || null);
  const isPrint = searchParams.get('print') === '1';

  useEffect(() => {
    if (isPrint && cv) {
      setTimeout(() => window.print(), 500);
    }
  }, [isPrint, cv]);

  if (isLoading) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center">
        <div className="animate-spin h-8 w-8 border-2 border-gray-900 border-t-transparent rounded-full" />
      </div>
    );
  }

  if (!cv) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center text-gray-500">
        CV not found or not published.
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white text-gray-900 print:bg-white">
      <div className="max-w-[800px] mx-auto p-8 sm:p-12">
        {/* Header */}
        <div className="border-b-2 border-gray-900 pb-6 mb-8">
          <h1 className="text-4xl font-bold tracking-tight text-gray-900">{cv.full_name}</h1>
          <p className="text-lg font-semibold text-gray-600 mt-1">{cv.position}</p>
          <p className="text-sm text-gray-500">{cv.current_team}</p>
        </div>

        {/* Profile Grid */}
        <div className="grid grid-cols-4 gap-4 mb-8 text-sm">
          {[
            { label: 'Age', value: cv.age },
            { label: 'Height', value: `${cv.height}cm` },
            { label: 'Weight', value: `${cv.weight}kg` },
            { label: 'Preferred Foot', value: cv.preferred_foot },
          ].map(item => (
            <div key={item.label} className="border border-gray-200 rounded p-3 text-center">
              <p className="text-[10px] uppercase tracking-wider text-gray-400">{item.label}</p>
              <p className="font-semibold text-gray-900 mt-0.5">{item.value}</p>
            </div>
          ))}
        </div>

        {/* Bio */}
        {cv.bio && (
          <div className="mb-8">
            <h3 className="text-[11px] uppercase tracking-widest text-gray-400 mb-2 font-semibold">Profile</h3>
            <p className="text-sm text-gray-700 leading-relaxed">{cv.bio}</p>
          </div>
        )}

        {/* Previous Teams */}
        {cv.previous_teams?.length > 0 && (
          <div className="mb-8">
            <h3 className="text-[11px] uppercase tracking-widest text-gray-400 mb-2 font-semibold">Previous Teams</h3>
            <div className="flex flex-wrap gap-2">
              {cv.previous_teams.map((t, i) => (
                <span key={i} className="px-3 py-1 bg-gray-100 text-gray-700 rounded text-sm">{t}</span>
              ))}
            </div>
          </div>
        )}

        {/* Achievements */}
        {cv.achievements?.length > 0 && (
          <div className="mb-8">
            <h3 className="text-[11px] uppercase tracking-widest text-gray-400 mb-2 font-semibold">Achievements</h3>
            <ul className="space-y-1">
              {cv.achievements.map((a, i) => (
                <li key={i} className="text-sm text-gray-700 flex items-center gap-2">
                  <div className="w-1.5 h-1.5 rounded-full bg-gray-900" />
                  {a}
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Highlight Video */}
        {cv.highlight_video_url && (
          <div className="mb-8">
            <h3 className="text-[11px] uppercase tracking-widest text-gray-400 mb-2 font-semibold">Highlights</h3>
            <a href={cv.highlight_video_url} target="_blank" rel="noopener noreferrer"
              className="inline-flex items-center gap-2 text-sm text-blue-600 hover:underline">
              <Link2 className="h-3.5 w-3.5" /> Watch Highlight Reel
            </a>
          </div>
        )}

        {/* Footer */}
        <div className="border-t border-gray-200 pt-6 mt-12 text-center">
          <p className="text-[10px] uppercase tracking-widest text-gray-400">
            Generated by Camino — Player Development Platform
          </p>
          <p className="text-[10px] text-gray-300 mt-1">camino-player-path.lovable.app</p>
        </div>
      </div>
    </div>
  );
}
