import { AbsoluteFill, useCurrentFrame, useVideoConfig, interpolate, spring } from "remotion";
import { loadFont } from "@remotion/google-fonts/PlusJakartaSans";
import { loadFont as loadInter } from "@remotion/google-fonts/Inter";

const { fontFamily } = loadFont("normal", { weights: ["800"], subsets: ["latin"] });
const { fontFamily: bodyFont } = loadInter("normal", { weights: ["500", "600", "700"], subsets: ["latin"] });

const BG = "#0A0C12";
const GOLD = "#E8B400";
const BLUE = "#2B7FE8";
const GREEN = "#1DB870";
const WHITE = "#F4F4F2";
const CARD = "#111827";

const STATS = [
  { label: "POSSESSION", val: "62%", color: BLUE },
  { label: "xG", val: "1.4", color: GOLD },
  { label: "SPRINTS", val: "47", color: GREEN },
  { label: "DISTANCE", val: "5.8 km", color: BLUE },
  { label: "PASSES", val: "284", color: GOLD },
  { label: "DUELS WON", val: "73%", color: GREEN },
];

export const FCHalfTimeStatsScene = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  // Stamp slam
  const stampS = spring({ frame, fps, config: { damping: 10, stiffness: 180 } });
  const stampScale = interpolate(stampS, [0, 1], [2.2, 1]);
  const stampOp = interpolate(frame, [0, 6], [0, 1], { extrapolateRight: "clamp" });
  const stampRot = interpolate(stampS, [0, 1], [-20, -8]);

  // Title
  const titleOp = interpolate(frame, [12, 28], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });

  return (
    <AbsoluteFill style={{ backgroundColor: BG, alignItems: "center", paddingTop: 130 }}>
      {/* HALF-TIME stamp */}
      <div style={{
        opacity: stampOp,
        transform: `scale(${stampScale}) rotate(${stampRot}deg)`,
        border: `5px solid ${GOLD}`, padding: "14px 36px", borderRadius: 12,
        marginBottom: 40,
      }}>
        <div style={{ fontFamily, fontWeight: 800, fontSize: 60, color: GOLD, letterSpacing: "0.06em", lineHeight: 1 }}>
          HALF-TIME · LIVE
        </div>
      </div>

      <div style={{ opacity: titleOp, fontFamily: bodyFont, fontSize: 26, color: "#9AA3B2", marginBottom: 40, fontWeight: 600, textAlign: "center", padding: "0 60px" }}>
        Walk off the pitch. Stats are already there.
      </div>

      {/* Stat cards grid */}
      <div style={{
        display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: 24,
        padding: "0 60px", width: "100%", boxSizing: "border-box", maxWidth: 960,
      }}>
        {STATS.map((s, i) => {
          const delay = 28 + i * 8;
          const sp = spring({ frame: frame - delay, fps, config: { damping: 16 } });
          const op = interpolate(frame, [delay, delay + 10], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
          const ty = interpolate(sp, [0, 1], [40, 0]);
          return (
            <div key={s.label} style={{
              backgroundColor: CARD, borderRadius: 18, padding: "32px 30px",
              border: `1px solid #1F2937`, opacity: op, transform: `translateY(${ty}px)`,
              boxShadow: `0 0 40px ${s.color}15`,
            }}>
              <div style={{ fontFamily: bodyFont, fontSize: 18, color: "#9AA3B2", letterSpacing: "0.18em", fontWeight: 600 }}>
                {s.label}
              </div>
              <div style={{ marginTop: 10, fontFamily, fontWeight: 800, fontSize: 72, color: s.color, lineHeight: 1, letterSpacing: "-0.03em" }}>
                {s.val}
              </div>
              {/* mini bar */}
              <div style={{ marginTop: 16, height: 5, backgroundColor: "#1C2230", borderRadius: 3, overflow: "hidden" }}>
                <div style={{
                  height: "100%", width: `${interpolate(frame - delay - 10, [0, 30], [0, 70 + i * 4], { extrapolateLeft: "clamp", extrapolateRight: "clamp" })}%`,
                  backgroundColor: s.color, borderRadius: 3,
                }} />
              </div>
            </div>
          );
        })}
      </div>

      {/* footer line */}
      <div style={{
        position: "absolute", bottom: 80, fontFamily: bodyFont, fontSize: 22, color: GOLD, letterSpacing: "0.32em", fontWeight: 600,
        opacity: interpolate(frame, [90, 110], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" }),
      }}>
        AUTO-GENERATED BY FOLLOWCAM
      </div>
    </AbsoluteFill>
  );
};
