// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.3.0";

// src/lib/mcp/tools/list-players.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@2.3.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-players.ts
var list_players_default = defineTool({
  name: "list_players",
  title: "List players",
  description: "List players visible to the signed-in user, optionally filtered by name, team or position.",
  inputSchema: {
    search: z.string().trim().nullable().describe("Filter by player name (partial match). Null for no filter."),
    position: z.string().trim().nullable().describe("Filter by position, e.g. 'Midfielder'. Null for no filter."),
    limit: z.number().int().min(1).max(100).nullable().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, position, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("players").select("id, name, age, position, team, age_group, overall_rating, attendance, jersey_number, is_public").order("overall_rating", { ascending: false }).limit(limit ?? 25);
    if (search) query = query.ilike("name", `%${search}%`);
    if (position) query = query.ilike("position", `%${position}%`);
    const { data, error } = await query;
    if (error) throw new ToolError(error.message);
    const players = (data ?? []).map((p) => ({
      id: p.id,
      name: p.name,
      age: p.age,
      position: p.position,
      team: p.team,
      ageGroup: p.age_group,
      overallRating: p.overall_rating,
      attendance: p.attendance,
      jerseyNumber: p.jersey_number,
      isPublic: p.is_public
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(players, null, 2) }],
      structuredContent: { players }
    };
  }
});

// src/lib/mcp/tools/get-player.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@2.3.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_player_default = defineTool2({
  name: "get_player",
  title: "Get player profile",
  description: "Get one player's full profile: bio, attribute groups (technical, tactical, physical, mental), recent evaluations and fitness tests.",
  inputSchema: { player_id: z2.string().uuid().describe("The player's id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ player_id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data: player, error } = await supabase.from("players").select("*").eq("id", player_id).maybeSingle();
    if (error) throw new ToolError2(error.message);
    if (!player) throw new ToolError2("Player not found or not visible to you.");
    const [{ data: evals }, { data: fitness }] = await Promise.all([
      supabase.from("evaluations").select("id, date, score, technical, tactical, physical, mental, notes").eq("player_id", player_id).order("date", { ascending: false }).limit(5),
      supabase.from("fitness_tests").select("id, test_date, beep_test_level, sprint_10m, sprint_30m, agility_time, vertical_jump, endurance_distance").eq("player_id", player_id).order("test_date", { ascending: false }).limit(3)
    ]);
    const profile = {
      id: player.id,
      name: player.name,
      age: player.age,
      position: player.position,
      team: player.team,
      ageGroup: player.age_group,
      nationality: player.nationality,
      preferredFoot: player.preferred_foot,
      heightCm: player.height,
      weightKg: player.weight,
      bio: player.bio,
      attendance: player.attendance,
      overallRating: player.overall_rating,
      attributes: {
        technical: player.technical ?? null,
        tactical: player.tactical ?? null,
        physical: player.physical ?? null,
        mental: player.mental ?? null
      },
      recentEvaluations: (evals ?? []).map((e) => ({
        id: e.id,
        date: e.date,
        score: e.score,
        technical: e.technical,
        tactical: e.tactical,
        physical: e.physical,
        mental: e.mental,
        notes: e.notes
      })),
      recentFitnessTests: (fitness ?? []).map((f) => ({
        id: f.id,
        testDate: f.test_date,
        beepTestLevel: f.beep_test_level,
        sprint10m: f.sprint_10m,
        sprint30m: f.sprint_30m,
        agilityTime: f.agility_time,
        verticalJump: f.vertical_jump,
        enduranceDistance: f.endurance_distance
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: { player: profile }
    };
  }
});

// src/lib/mcp/tools/create-evaluation.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@2.3.0";
import { z as z3 } from "npm:zod@^3.25.76";
var rating = z3.number().min(0).max(100);
var create_evaluation_default = defineTool3({
  name: "create_evaluation",
  title: "Record a player evaluation",
  description: "Record a new evaluation for a player with technical, tactical, physical and mental ratings (0-100) and optional notes.",
  inputSchema: {
    player_id: z3.string().uuid().describe("The player's id."),
    date: z3.string().nullable().describe("Evaluation date as YYYY-MM-DD. Null uses today."),
    technical: rating.describe("Technical rating 0-100."),
    tactical: rating.describe("Tactical rating 0-100."),
    physical: rating.describe("Physical rating 0-100."),
    mental: rating.describe("Mental rating 0-100."),
    notes: z3.string().trim().nullable().describe("Coach notes. Null for none.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ player_id, date, technical, tactical, physical, mental, notes }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const score = Number(
      (technical * 0.4 + tactical * 0.3 + physical * 0.2 + mental * 0.1).toFixed(1)
    );
    const { data, error } = await supabase.from("evaluations").insert({
      player_id,
      evaluated_by: ctx.getUserId(),
      date: date || (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      technical,
      tactical,
      physical,
      mental,
      score,
      notes: notes?.trim() || null
    }).select("id, player_id, date, score").single();
    if (error) throw new ToolError3(error.message);
    const evaluation = { id: data.id, playerId: data.player_id, date: data.date, score: data.score };
    return {
      content: [{ type: "text", text: `Evaluation saved (score ${evaluation.score}).` }],
      structuredContent: { evaluation }
    };
  }
});

// src/lib/mcp/tools/add-player-feedback.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@2.3.0";
import { z as z4 } from "npm:zod@^3.25.76";
var add_player_feedback_default = defineTool4({
  name: "add_player_feedback",
  title: "Add coach feedback",
  description: "Write coach feedback for a player: strengths, areas to improve and extra notes.",
  inputSchema: {
    player_id: z4.string().uuid().describe("The player's id."),
    strengths: z4.string().trim().min(1).describe("What the player does well."),
    improvements: z4.string().trim().min(1).describe("What the player should work on."),
    notes: z4.string().trim().nullable().describe("Additional notes. Null for none.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ player_id, strengths, improvements, notes }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("player_feedback").insert({
      player_id,
      coach_id: ctx.getUserId(),
      strengths,
      improvements,
      notes: notes?.trim() || ""
    }).select("id, player_id, created_at").single();
    if (error) throw new ToolError4(error.message);
    const feedback = { id: data.id, playerId: data.player_id, createdAt: data.created_at };
    return {
      content: [{ type: "text", text: "Feedback saved for the player." }],
      structuredContent: { feedback }
    };
  }
});

// src/lib/mcp/tools/list-training-sessions.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@2.3.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_training_sessions_default = defineTool5({
  name: "list_training_sessions",
  title: "List training sessions",
  description: "List upcoming or recent training sessions visible to the signed-in user.",
  inputSchema: {
    upcoming_only: z5.boolean().nullable().describe("True for future sessions only. Null lists all."),
    limit: z5.number().int().min(1).max(100).nullable().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ upcoming_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError5("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("training_sessions").select("id, name, description, session_date, focus_area").order("session_date", { ascending: false }).limit(limit ?? 20);
    if (upcoming_only) query = query.gte("session_date", (/* @__PURE__ */ new Date()).toISOString());
    const { data, error } = await query;
    if (error) throw new ToolError5(error.message);
    const sessions = (data ?? []).map((s) => ({
      id: s.id,
      name: s.name,
      description: s.description,
      sessionDate: s.session_date,
      focusArea: s.focus_area
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(sessions, null, 2) }],
      structuredContent: { sessions }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cilfhtailwwlynunmrqw";
var mcp_default = defineMcp({
  name: "camino-player-journey",
  title: "Camino: Player Journey",
  version: "0.1.0",
  instructions: "Tools for Camino, a soccer player development platform. Use `list_players` and `get_player` to read squad and player development data, `create_evaluation` to record technical/tactical/physical/mental ratings, `add_player_feedback` to write coach feedback, and `list_training_sessions` for the training schedule. All tools act as the signed-in Camino user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_players_default,
    get_player_default,
    create_evaluation_default,
    add_player_feedback_default,
    list_training_sessions_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.3.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
